import { readFile, writeFile } from "node:fs/promises";

const source = await readFile(new URL("../../src/data/regions.ts", import.meta.url), "utf8");
const version = source.match(/CURRICULUM_VERSION\s*=\s*(\d+)/)?.[1];
const regions = [...source.matchAll(/\[(\d+),\s*"[^"]*",\s*"[^"]*",\s*"([^"]+)"\]/g)];
if (!version || !regions.length) throw new Error("Could not read the curriculum manifest from src/data/regions.ts.");
const ids = regions.map((match) => Number(match[1])).sort((a, b) => a - b);
const chars = regions.map((match) => match[2]).join("");
if (new Set(ids).size !== ids.length || new Set([...chars]).size !== [...chars].length) throw new Error("Duplicate curriculum IDs or characters.");
const output = `// Generated by backend/scripts/generate-curriculum.ts from src/data/regions.ts.\n// Run this script when the curriculum changes; runtime has no frontend dependency.\nexport const CURRICULUM_VERSION = ${version};\nexport const CHAPTER_IDS = ${JSON.stringify(ids)} as const;\nexport const KANJI_CHARACTERS = ${JSON.stringify(chars)};\n`;
await writeFile(new URL("../src/domain/curriculum.ts", import.meta.url), output);
console.log(`Generated curriculum ${version}: ${ids.length} chapters and ${[...chars].length} kanji.`);
