/** Original sentence drafts. Not imported by the application: native review is pending. */
export type SentenceDraft = { region: number; ruby: string; translation: string; slot: string; pos: "noun" | "time" | "verb" | "adjective"; reviewed: false; source: "original" };
type DraftRow = [region: number, ruby: string, translation: string, slot: string, pos: SentenceDraft["pos"]];
const rows: DraftRow[] = [
  [1, "りんごが一[ひと]つあります。", "There is one apple.", "一つ", "noun"],
  [1, "みかんを三[みっ]つください。", "Three mandarins, please.", "三つ", "noun"],
  [13, "ここに六[むっ]つあります。", "There are six here.", "六つ", "noun"],
  [13, "りんごを七[なな]つください。", "Seven apples, please.", "七つ", "noun"],
  [14, "これは三[さん]百[びゃく]円[えん]です。", "This costs three hundred yen.", "三百円", "noun"],
  [14, "いまは四[よ]時[じ]です。", "It is four o'clock now.", "四時", "time"],
  [2, "月[つき]がきれいです。", "The moon is beautiful.", "月", "noun"],
  [2, "水[みず]をください。", "Water, please.", "水", "noun"],
  [15, "金[きん]曜[よう]日[び]にあいましょう。", "Let's meet on Friday.", "金曜日", "time"],
  [15, "土[ど]曜[よう]日[び]はひまです。", "I am free on Saturday.", "土曜日", "time"],
  [16, "今[いま]は朝[あさ]です。", "It is morning now.", "朝", "time"],
  [16, "毎[まい]朝[あさ]、水[みず]をのみます。", "I drink water every morning.", "毎朝", "time"],
  [3, "友[とも]だちの名[な]前[まえ]はあきです。", "My friend's name is Aki.", "名前", "noun"],
  [3, "夜[よる]はしずかです。", "It is quiet at night.", "夜", "time"],
  [17, "父[ちち]はここにいます。", "My father is here.", "父", "noun"],
  [17, "母[はは]とあいます。", "I will meet my mother.", "母", "noun"],
  [18, "右[みぎ]をみてください。", "Please look to the right.", "右", "noun"],
  [18, "左[ひだり]に木[き]があります。", "There is a tree on the left.", "左", "noun"],
  [4, "大[おお]きい木[き]があります。", "There is a big tree.", "大きい", "adjective"],
  [4, "小[ちい]さい子[こ]がいます。", "There is a small child.", "小さい", "adjective"],
  [19, "これは安[やす]いです。", "This is inexpensive.", "安い", "adjective"],
  [19, "ここは人[ひと]が多[おお]いです。", "There are many people here.", "多い", "adjective"],
  [20, "新[あたら]しいくつです。", "These are new shoes.", "新しい", "adjective"],
  [20, "朝[あさ]は早[はや]いです。", "It is early in the morning.", "早い", "adjective"],
  [21, "赤[あか]いりんごをください。", "A red apple, please.", "赤い", "adjective"],
  [21, "白[しろ]いくつがあります。", "There are white shoes.", "白い", "adjective"],
  [5, "名[な]前[まえ]を書[か]いてください。", "Please write your name.", "書いて", "verb"],
  [5, "母[はは]の話[はなし]を聞[き]きます。", "I listen to my mother talk.", "聞きます", "verb"],
  [22, "朝[あさ]、りんごを食[た]べます。", "I eat an apple in the morning.", "食べます", "verb"],
  [22, "水[みず]を飲[の]みます。", "I drink water.", "飲みます", "verb"],
  [23, "六[ろく]時[じ]に帰[かえ]ります。", "I return home at six.", "帰ります", "verb"],
  [23, "友[とも]だちが来[き]ます。", "A friend is coming.", "来ます", "verb"],
  [6, "毎[まい]日[にち]、学[がっ]校[こう]に行[い]きます。", "I go to school every day.", "学校", "noun"],
  [6, "先[せん]生[せい]の話[はなし]を聞[き]きます。", "I listen to the teacher.", "先生", "noun"],
  [24, "駅[えき]で友[とも]だちにあいます。", "I meet a friend at the station.", "駅", "noun"],
  [24, "あの店[みせ]は安[やす]いです。", "That shop is inexpensive.", "店", "noun"],
  [25, "山[やま]の上[うえ]はしずかです。", "It is quiet on the mountain.", "山", "noun"],
  [25, "今日[きょう]は雨[あめ]です。", "It is rainy today.", "雨", "noun"],
  [7, "私[わたし]は本[ほん]を読[よ]みます。", "I read a book.", "本", "noun"],
  [7, "外[そと]に友[とも]だちがいます。", "A friend is outside.", "外", "noun"],
  [26, "兄[あに]は学[がく]生[せい]です。", "My older brother is a student.", "兄", "noun"],
  [26, "妹[いもうと]と学[がっ]校[こう]に行[い]きます。", "I go to school with my younger sister.", "妹", "noun"],
  [27, "家[いえ]の前[まえ]に木[き]があります。", "There is a tree in front of the house.", "家", "noun"],
  [27, "住[じゅう]所[しょ]を書[か]いてください。", "Please write your address.", "住所", "noun"],
  [28, "門[もん]の前[まえ]で会[あ]いましょう。", "Let's meet in front of the gate.", "門", "noun"],
  [28, "新[あたら]しい服[ふく]を買[か]いました。", "I bought new clothes.", "服", "noun"],
  [29, "同[おな]じ本[ほん]を読[よ]んでいます。", "We are reading the same book.", "同じ", "adjective"],
  [29, "私[わたし]は雨[あめ]が好[す]きです。", "I like rain.", "好き", "adjective"],
  [30, "手[て]を上[あ]げてください。", "Please raise your hand.", "手", "noun"],
  [30, "口[くち]を開[あ]けてください。", "Please open your mouth.", "口", "noun"],
  [8, "漢[かん]字[じ]を書[か]きます。", "I write kanji.", "漢字", "noun"],
  [8, "白[しろ]い紙[かみ]をください。", "White paper, please.", "紙", "noun"],
  [31, "毎[まい]日[にち]、勉[べん]強[きょう]します。", "I study every day.", "勉強", "noun"],
  [31, "試[し]験[けん]は月[げつ]曜[よう]日[び]です。", "The examination is on Monday.", "試験", "noun"],
  [32, "質[しつ]問[もん]があります。", "I have a question.", "質問", "noun"],
  [32, "答[こた]えを書[か]いてください。", "Please write the answer.", "答え", "noun"],
  [33, "その話[はなし]は知[し]っています。", "I know that story.", "知って", "verb"],
  [33, "正[ただ]しい答[こた]えは三[さん]です。", "The correct answer is three.", "正しい", "adjective"],
  [34, "この図[ず]を見[み]てください。", "Please look at this diagram.", "図", "noun"],
  [34, "時[じ]間[かん]を計[はか]ります。", "I measure the time.", "計ります", "verb"],
  [35, "これは特[とく]別[べつ]な日[ひ]です。", "This is a special day.", "特別", "adjective"],
  [35, "父[ちち]は元[げん]気[き]です。", "My father is well.", "元気", "adjective"],
  [9, "北[きた]に大[おお]きい山[やま]があります。", "There is a big mountain to the north.", "北", "noun"],
  [9, "東[とう]京[きょう]に行[い]きます。", "I am going to Tokyo.", "東京", "noun"],
  [36, "この町[まち]はしずかです。", "This town is quiet.", "町", "noun"],
  [36, "村[むら]に小[ちい]さい学[がっ]校[こう]があります。", "There is a small school in the village.", "村", "noun"],
  [37, "この道[みち]をまっすぐ行[い]ってください。", "Please go straight along this road.", "道", "noun"],
  [37, "毎[まい]朝[あさ]、歩[ある]きます。", "I walk every morning.", "歩きます", "verb"],
  [38, "駅[えき]で電[でん]車[しゃ]に乗[の]ります。", "I board the train at the station.", "乗ります", "verb"],
  [38, "急[いそ]いで学[がっ]校[こう]に行[い]きます。", "I hurry to school.", "急いで", "verb"],
  [39, "家[いえ]は駅[えき]から近[ちか]いです。", "My house is near the station.", "近い", "adjective"],
  [39, "遠[とお]い町[まち]に友[とも]だちがいます。", "I have a friend in a faraway town.", "遠い", "adjective"],
  [40, "新[あたら]しい家[いえ]を建[た]てます。", "We are building a new house.", "建てます", "verb"],
  [40, "世[せ]界[かい]には多[おお]くの国[くに]があります。", "There are many countries in the world.", "世界", "noun"],
  [10, "父[ちち]は会[かい]社[しゃ]で働[はたら]いています。", "My father works at a company.", "働いて", "verb"],
  [10, "仕[し]事[ごと]は五[ご]時[じ]までです。", "Work lasts until five o'clock.", "仕事", "noun"],
  [41, "駅[えき]で友[とも]だちを待[ま]ちます。", "I wait for a friend at the station.", "待ちます", "verb"],
  [41, "この紙[かみ]を使[つか]ってください。", "Please use this paper.", "使って", "verb"],
  [42, "試[し]験[けん]は九[く]時[じ]に始[はじ]まります。", "The exam starts at nine.", "始まります", "verb"],
  [42, "仕[し]事[ごと]が終[お]わりました。", "Work is finished.", "終わりました", "verb"],
  [43, "友[とも]だちに本[ほん]を貸[か]します。", "I lend a book to a friend.", "貸します", "verb"],
  [43, "この店[みせ]は本[ほん]を売[う]っています。", "This shop sells books.", "売って", "verb"],
  [44, "昼[ひる]に魚[さかな]を食[た]べます。", "I eat fish at lunchtime.", "魚", "noun"],
  [44, "午[ご]後[ご]は家[いえ]にいます。", "I am at home in the afternoon.", "午後", "time"],
  [45, "店[てん]員[いん]に聞[き]いてください。", "Please ask a shop assistant.", "店員", "noun"],
  [45, "友[とも]だちが家[いえ]に集[あつ]まります。", "Friends gather at my house.", "集まります", "verb"],
  [11, "春[はる]はあたたかいです。", "Spring is warm.", "春", "time"],
  [11, "冬[ふゆ]は日[ひ]がみじかいです。", "The days are short in winter.", "冬", "time"],
  [46, "夏[なつ]に海[うみ]に行[い]きます。", "I go to the sea in summer.", "海", "noun"],
  [46, "森[もり]の中[なか]を歩[ある]きます。", "I walk through the forest.", "森", "noun"],
  [47, "犬[いぬ]と外[そと]を歩[ある]きます。", "I walk outside with my dog.", "犬", "noun"],
  [47, "木[き]の上[うえ]に鳥[とり]がいます。", "There is a bird in the tree.", "鳥", "noun"],
  [48, "朝[あさ]ご飯[はん]を食[た]べます。", "I eat breakfast.", "朝ご飯", "noun"],
  [48, "お茶[ちゃ]を飲[の]みましょう。", "Let's drink some tea.", "お茶", "noun"],
  [49, "赤[あか]い花[はな]を買[か]いました。", "I bought red flowers.", "花", "noun"],
  [49, "風[かぜ]の音[おと]を聞[き]きます。", "I listen to the sound of the wind.", "音", "noun"],
  [50, "友[とも]だちと映[えい]画[が]を見[み]ます。", "I watch a film with a friend.", "映画", "noun"],
  [50, "母[はは]の歌[うた]が好[す]きです。", "I like my mother's songs.", "歌", "noun"],
  [12, "名[な]前[まえ]を大[おお]きい声[こえ]で言[い]ってください。", "Please say your name in a loud voice.", "声", "noun"],
  [12, "朝[あさ]、顔[かお]をあらいます。", "I wash my face in the morning.", "顔", "noun"],
  [51, "病[びょう]院[いん]は駅[えき]の前[まえ]です。", "The hospital is in front of the station.", "病院", "noun"],
  [51, "薬[くすり]を水[みず]で飲[の]みます。", "I take medicine with water.", "薬", "noun"],
  [52, "今日[きょう]は気[き]分[ぶん]が悪[わる]いです。", "I feel unwell today.", "悪い", "adjective"],
  [52, "弟[おとうと]は力[ちから]があります。", "My younger brother is strong.", "力", "noun"],
  [53, "毎[まい]朝[あさ]、六[ろく]時[じ]に起[お]きます。", "I get up at six every morning.", "起きます", "verb"],
  [53, "食[た]べる前[まえ]に手[て]を洗[あら]います。", "I wash my hands before eating.", "洗います", "verb"],
  [54, "この本[ほん]は軽[かる]いです。", "This book is light.", "軽い", "adjective"],
  [54, "今日[きょう]は寒[さむ]いです。", "It is cold today.", "寒い", "adjective"],
  [55, "この家[いえ]は広[ひろ]いです。", "This house is spacious.", "広い", "adjective"],
  [55, "食[しょく]堂[どう]で昼[ひる]ご飯[はん]を食[た]べます。", "I eat lunch in the dining hall.", "食堂", "noun"],
];

export const sentenceDrafts: SentenceDraft[] = rows.map(([region, ruby, translation, slot, pos]) => ({ region, ruby, translation, slot, pos, reviewed: false, source: "original" }));
