// Generated by backend/scripts/generate-curriculum.ts from src/data/regions.ts.
// Run this script when the curriculum changes; runtime has no frontend dependency.
export const CURRICULUM_VERSION = 2;
export const CHAPTER_IDS = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55] as const;
export const KANJI_CHARACTERS = "一二三四五六七八九十百千万円時分日月火水木金土曜年週半今先毎朝昼人友名前夜男女子父母後右左中上下大小長間高安多少新古早何白赤青黒見聞読書話言食飲買立休行来帰入出学校生語目耳国電車駅店天気雨山川本外社私自会族親兄姉弟妹家主住所屋室門開服着物品同合別方心好便不有手足口文字漢英紙教習勉強試験質問題答考思意知理正説計研究図用代以特真元北南東西京都県市区町村地公場道通走歩乗運転発進急空近遠旅送建工台世界仕事働作業持待使引切始終止動去借貸売銀産肉魚午注回集員民度春夏秋冬夕海池森林洋田野犬鳥牛菜飯味料茶花光風色音写楽歌映画館体顔頭声首医者病院薬力弱悪死起洗明暗軽重暑寒広太短低堂";
