/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampRouteImport } from './routes/camp'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as MapRouteImport } from './routes/map'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RunRouteImport } from './routes/run'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampRoute = CampRouteImport.update({
  id: '/camp',
  path: '/camp',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camp': typeof CampRoute
  '/collection': typeof CollectionRoute
  '/map': typeof MapRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/run': typeof RunRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camp': typeof CampRoute
  '/collection': typeof CollectionRoute
  '/map': typeof MapRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/run': typeof RunRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camp': typeof CampRoute
  '/collection': typeof CollectionRoute
  '/map': typeof MapRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/run': typeof RunRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camp'
    | '/collection'
    | '/map'
    | '/practice'
    | '/privacy'
    | '/run'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camp'
    | '/collection'
    | '/map'
    | '/practice'
    | '/privacy'
    | '/run'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/camp'
    | '/collection'
    | '/map'
    | '/practice'
    | '/privacy'
    | '/run'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampRoute: typeof CampRoute
  CollectionRoute: typeof CollectionRoute
  MapRoute: typeof MapRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  RunRoute: typeof RunRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp': {
      id: '/camp'
      path: '/camp'
      fullPath: '/camp'
      preLoaderRoute: typeof CampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampRoute: CampRoute,
  CollectionRoute: CollectionRoute,
  MapRoute: MapRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  RunRoute: RunRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
